#!/usr/bin/env bash
# 
# Shell aliases customization
#
# © 2012-2015 Łukasz Pietrek
# https://www.debian.org/legal/licenses/mit
#
# TODO: this file need better names :]


main_bash_alias () {
  put_colors_into_my_world
  searching_teaks
  system_behavior
  quick_navigation
}


put_colors_into_my_world () {
  if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
  fi
}


searching_teaks () {
  alias ll='ls -alF'
  alias la='ls -A'
  alias l='ls -CF'
}


system_behavior () {
  alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
}


quick_navigation () {
  alias ..='cd ..'
  alias ...='cd ../../'
  alias ....='cd ../../../'
  alias .....='cd ../../../../'
  alias ......='cd ../../../../../'
}


main_bash_alias
