
source_prompt () {
  if [ -f ~/.bash_prompt ]; then
      . ~/.bash_prompt
  fi
}


source_aliases () {
  if [ -f ~/.bash_aliases ]; then
      . ~/.bash_aliases
  fi
}


enable_programmable_completion_features () {
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
    fi
  fi
}


modify_bash_behavior () {
  shopt -s checkwinsize
  shopt -s histappend
  shopt -s globstar
  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
}


set_shell_variables () {
  HISTCONTROL=ignoreboth
  HISTSIZE=1000
  HISTFILESIZE=2000
}


set_and_export_variables () {
  export COLORFGBG="default;default"
  export PROMPT_COMMAND="__git_aware_prompt"
  export EDITOR="vim"
  export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
}


main () {
  set_shell_variables
  modify_bash_behavior
  source_prompt
  source_aliases
  set_and_export_variables
}


run_if_interactive () {
  case $- in
      *i*) main $@;;
        *) return;;
  esac
}

run_if_interactive