#!/usr/bin/env bash
# 
# PS1 customization
#
# © 2012-2015 Łukasz Pietrek
# https://www.debian.org/legal/licenses/mit


main_bash_prompt () {
  if i_can_use_color_prompt; then 
    use_color_prompt
  else 
    use_basic_prompt
  fi
}


i_can_use_color_prompt () {
  [[ $TERM == "xterm-color" ]] || [[ $force_color_prompt == "yes" ]] || [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null;
}


use_color_prompt () {
  declare_color_variables_for_ps1_prompt
  declare_format_variables_for_ps1_prompt
  export PROMPT_COMMAND="ps1_color_prompt"
}


use_basic_prompt () {
  declare_format_variables_for_ps1_prompt
  export PROMPT_COMMAND="ps1_basic_prompt"
}


ps1_color_prompt () {
  local debian_chroot=$(get_debian_chroot)
  local user="$BICyan$User$BIBlack@$Cyan$Host$Color_Off"
  local path="$BIBlack:$BIBlue$PathShort"
  if i_am_root; then
    user="$BIRed$User$BIBlack@$Cyan$Host$Color_Off";
  fi
  PS1="$debian_chroot$IYellow[$user$path$IYellow]\$$Color_Off "
}


ps1_basic_prompt () {
  local debian_chroot=$(get_debian_chroot)
  export PS1="$get_debian_chroot[$User@$Host:$PathShort]\$ "
}


i_am_root () {
  [[ $EUID -eq 0 ]]
}


get_debian_chroot () {
  local debian_chroot=""
  if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
  fi
  case "$TERM" in
    xterm*|\
     rxvt*) debian_chroot="${debian_chroot:+($debian_chroot)}";;
         *) ;;
  esac
  echo $debian_chroot
}


declare_format_variables_for_ps1_prompt () {
  Time12h="\T"
  Time12a="\@"
  PathShort="\w"
  PathFull="\W"
  NewLine="\n"
  Jobs="\j"
  User="\u"
  Host="\h"
}


declare_color_variables_for_ps1_prompt () {
  # Reset
  Color_Off="\[\033[0m\]"       # Text Reset

  # Regular Colors
  Black="\[\033[0;30m\]"        # Black
  Red="\[\033[0;31m\]"          # Red
  Green="\[\033[0;32m\]"        # Green
  Yellow="\[\033[0;33m\]"       # Yellow
  Blue="\[\033[0;34m\]"         # Blue
  Purple="\[\033[0;35m\]"       # Purple
  Cyan="\[\033[0;36m\]"         # Cyan
  White="\[\033[0;37m\]"        # White

  # Bold
  BBlack="\[\033[1;30m\]"       # Black
  BRed="\[\033[1;31m\]"         # Red
  BGreen="\[\033[1;32m\]"       # Green
  BYellow="\[\033[1;33m\]"      # Yellow
  BBlue="\[\033[1;34m\]"        # Blue
  BPurple="\[\033[1;35m\]"      # Purple
  BCyan="\[\033[1;36m\]"        # Cyan
  BWhite="\[\033[1;37m\]"       # White

  # Underline
  UBlack="\[\033[4;30m\]"       # Black
  URed="\[\033[4;31m\]"         # Red
  UGreen="\[\033[4;32m\]"       # Green
  UYellow="\[\033[4;33m\]"      # Yellow
  UBlue="\[\033[4;34m\]"        # Blue
  UPurple="\[\033[4;35m\]"      # Purple
  UCyan="\[\033[4;36m\]"        # Cyan
  UWhite="\[\033[4;37m\]"       # White

  # Background
  On_Black="\[\033[40m\]"       # Black
  On_Red="\[\033[41m\]"         # Red
  On_Green="\[\033[42m\]"       # Green
  On_Yellow="\[\033[43m\]"      # Yellow
  On_Blue="\[\033[44m\]"        # Blue
  On_Purple="\[\033[45m\]"      # Purple
  On_Cyan="\[\033[46m\]"        # Cyan
  On_White="\[\033[47m\]"       # White

  # High Intensty
  IBlack="\[\033[0;90m\]"       # Black
  IRed="\[\033[0;91m\]"         # Red
  IGreen="\[\033[0;92m\]"       # Green
  IYellow="\[\033[0;93m\]"      # Yellow
  IBlue="\[\033[0;94m\]"        # Blue
  IPurple="\[\033[0;95m\]"      # Purple
  ICyan="\[\033[0;96m\]"        # Cyan
  IWhite="\[\033[0;97m\]"       # White

  # Bold High Intensty
  BIBlack="\[\033[1;90m\]"      # Black
  BIRed="\[\033[1;91m\]"        # Red
  BIGreen="\[\033[1;92m\]"      # Green
  BIYellow="\[\033[1;93m\]"     # Yellow
  BIBlue="\[\033[1;94m\]"       # Blue
  BIPurple="\[\033[1;95m\]"     # Purple
  BICyan="\[\033[1;96m\]"       # Cyan
  BIWhite="\[\033[1;97m\]"      # White

  # High Intensty backgrounds
  On_IBlack="\[\033[0;100m\]"   # Black
  On_IRed="\[\033[0;101m\]"     # Red
  On_IGreen="\[\033[0;102m\]"   # Green
  On_IYellow="\[\033[0;103m\]"  # Yellow
  On_IBlue="\[\033[0;104m\]"    # Blue
  On_IPurple="\[\033[10;95m\]"  # Purple
  On_ICyan="\[\033[0;106m\]"    # Cyan
  On_IWhite="\[\033[0;107m\]"   # White
}


main_bash_prompt


unset -f main_bash_prompt
unset -f i_can_use_color_prompt
unset -f use_color_prompt
unset -f use_basic_prompt
unset -f ps1_color_prompt
unset -f ps1_basic_prompt
unset -f i_am_root
unset -f get_debian_chroot
unset -f declare_format_variables_for_ps1_prompt
unset -f declare_color_variables_for_ps1_prompt
