#!/usr/bin/env bash
# 
# Profile customization
#
# © 2012-2015 Łukasz Pietrek
# https://www.debian.org/legal/licenses/mit


main_profile () {
  set_files_properties
  run_bashrc
  register_custom_executables
}


set_files_properties () {
  umask 022
}


run_bashrc () {
  if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
      . "$HOME/.bashrc"
    fi
  fi
}


register_custom_executables () {
  if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
  fi
}


main_profile


unset -f main_profile
unset -f set_files_properties
unset -f run_bashrc
unset -f register_custom_executables
