#!/usr/bin/env fish


##################################################
# WARNING:
#
# This script install fisher and some plugins.
#
# Use case is: recreation of fish configuration
# from scratch.
#
# So dont run this file if you want to use
# configuration from this repo or you will face
# conflicts.
##################################################

curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source

fisher install jorgebucaran/fisher
fisher install jorgebucaran/nvm.fish
fisher install PatrickF1/fzf.fish
fisher install IlanCosman/tide@v6
