#!/usr/bin/env fish


set version 18.6.1
set file ltex-ls-plus-18.6.1-linux-x64.tar.gz
set url https://github.com/ltex-plus/ltex-ls-plus/releases/download/$version/$file




pushd $HOME/user/download
  wget $url -O $file
  tar xf $file
popd
