#!/usr/bin/env bash

mkdir -p $HOME/utils

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip htop nvm btop bat

## snap install zig --classic --beta

target=$HOME/utils/fzf
git clone https://github.com/junegunn/fzf $target

. $target/install
