#!/usr/bin/env bash

mkdir -p $HOME/utils

sudo apt -y update
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip htop nvm

## snap install zig --classic --beta

git clone https://github.com/junegunn/fzf $HOME/utils/fzf

$HOME/utils/fzf/install
