#!/usr/bin/env bash

mkdir -p $HOME/utils

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip htop nvm btop bat

## snap install zig --classic --beta

target=$HOME/utils/fzf
git clone https://github.com/junegunn/fzf $target

. $target/install

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh



set VERSION latest
set BINARY yq_linux_amd64
set yq_url "https://github.com/mikefarah/yq/releases/download/$VERSION/$BINARY"
set yq_target $HOME/.local/bin/yq

wget "$yq_url" -O "$yq_target" && chmod +x "$yq_target"
