#!/usr/bin/env bash

sudo apt install -y build-essential libreadline-dev unzip

rm -rf /tmp/luarocks
mkdir -p /tmp/luarocks

pushd /tmp/luarocks
  version="5.4.7"
  curl -L -R -O https://www.lua.org/ftp/lua-$version.tar.gz
  tar -zxf lua-$version.tar.gz
  pushd lua-$version
    make linux test
    sudo make install
  popd



  wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
  tar zxpf luarocks-3.11.1.tar.gz
  pushd luarocks-3.11.1
    ./configure --with-lua-include=/usr/local/include 
    make 
    sudo make install
  popd
popd
