#!/usr/bin/env fish

#sudo apt install glslang-tools libcairo2-dev libcap-dev libdbus-1-dev libdisplay-info-dev libevdev-dev libgdk-pixbuf2.0-dev libinput-dev libjson-c-dev libliftoff-dev libpam0g-dev libpango1.0-dev libpcre2-dev libpixman-1-dev libseat-dev libsystemd-dev libvulkan-dev libwayland-dev libwayland-egl1 libwlroots-dev libxcb-ewmh-dev libxkbcommon-dev meson pkgconf scdoc tree wayland-protocols

set target $HOME/utils/sway_wm

#git clone --depth=1 https://github.com/swaywm/sway $target

pushd $target &> /dev/null


  #git clone --depth=1 https://gitlab.freedesktop.org/wlroots/wlroots.git subprojects/wlroots

  meson setup build/
  ninja -C build/
  build/sway/sway


popd
