#!/usr/bin/env fish

set -gx TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tpm-plugins"
set target $HOME/.local/share/tpm

sudo apt install tmux

rm -rf $target
git clone https://github.com/tmux-plugins/tpm $target

bash $target/scripts/install_plugins.sh
