# vim:syntax=i3config

set $NumLock mod2

# Change focus between two last workspaces
bindsym $mod+Tab workspace back_and_forth


# Use keypad numbers for navigation between numbered workspaces
#
# i3 on itself does not recognize binding to Key Pad Digits on their own
# they must be always acompanied by NumLock key.
bindsym $NumLock+KP_0 workspace $WS_0
bindsym $NumLock+KP_1 workspace $WS_1
bindsym $NumLock+KP_2 workspace $WS_2
bindsym $NumLock+KP_3 workspace $WS_3
bindsym $NumLock+KP_4 workspace $WS_4
bindsym $NumLock+KP_5 workspace $WS_5
bindsym $NumLock+KP_6 workspace $WS_6
bindsym $NumLock+KP_7 workspace $WS_7
bindsym $NumLock+KP_8 workspace $WS_8
bindsym $NumLock+KP_9 workspace $WS_9
bindsym $NumLock+Shift+KP_0 move container to workspace number $WS_0
bindsym $NumLock+Shift+KP_1 move container to workspace number $WS_1
bindsym $NumLock+Shift+KP_2 move container to workspace number $WS_2
bindsym $NumLock+Shift+KP_3 move container to workspace number $WS_3
bindsym $NumLock+Shift+KP_4 move container to workspace number $WS_4
bindsym $NumLock+Shift+KP_5 move container to workspace number $WS_5
bindsym $NumLock+Shift+KP_6 move container to workspace number $WS_6
bindsym $NumLock+Shift+KP_7 move container to workspace number $WS_7
bindsym $NumLock+Shift+KP_8 move container to workspace number $WS_8
bindsym $NumLock+Shift+KP_9 move container to workspace number $WS_9

# Key Pad Keys are used without NumLock... duh
bindsym KP_Insert workspace $WS_0
bindsym KP_End workspace $WS_1
bindsym KP_Down workspace $WS_2
bindsym KP_Next workspace $WS_3
bindsym KP_Left workspace $WS_4
bindsym KP_Begin workspace $WS_5
bindsym KP_Right workspace $WS_6
bindsym KP_Home workspace $WS_7
bindsym KP_Up workspace $WS_8
bindsym KP_Prior workspace $WS_9
bindsym Shift+KP_Insert move container to workspace number $WS_0
bindsym Shift+KP_End move container to workspace number $WS_1
bindsym Shift+KP_Down move container to workspace number $WS_2
bindsym Shift+KP_Next move container to workspace number $WS_3
bindsym Shift+KP_Left move container to workspace number $WS_4
bindsym Shift+KP_Begin move container to workspace number $WS_5
bindsym Shift+KP_Right move container to workspace number $WS_6
bindsym Shift+KP_Home move container to workspace number $WS_7
bindsym Shift+KP_Up move container to workspace number $WS_8
bindsym Shift+KP_Prior move container to workspace number $WS_9
