# vim:syntax=i3config
#
set $resize_mode "Drag border or use arrow keys to resize. Esc to exit mode."
mode $resize_mode {
        bindsym Left resize shrink width 50 px or 50 ppt
        bindsym Down resize grow height 50 px or 50 ppt
        bindsym Up resize shrink height 50 px or 50 ppt
        bindsym Right resize grow width 50 px or 50 ppt

        bindsym Shift+Left resize shrink width 150 px or 150 ppt
        bindsym Shift+Down resize grow height 150 px or 150 ppt
        bindsym Shift+Up resize shrink height 150 px or 150 ppt
        bindsym Shift+Right resize grow width 150 px or 150 ppt

        bindsym Escape mode "default"
}
bindsym $mod+r mode $resize_mode
