# vim:syntax=i3config

# set $chat_exec /opt/microsoft/msedge/microsoft-edge --profile-directory=Default --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo "--app-url=https://teams.microsoft.com/v2/?clientType=pwa"
#
# set $mail_exec /opt/microsoft/msedge/microsoft-edge --profile-directory=Default --app-id=faolnafnngnfdaknnbpnkhgohbobgegn --app-url=https://outlook.office.com/mail/
#
# exec --no-startup-id $chat_exec,
# exec --no-startup-id $mail_exec,
#


# set $layout_dev_base /home/lukasz_pietrek/.config/i3/layouts/dev-base.json



# exec --no-startup-id i3-msg 'workspace $ws1; append_layout $layout_dev_base'
# exec --no-startup-id i3-msg 'workspace $ws2; append_layout $layout_dev_base'
# exec --no-startup-id i3-msg 'workspace $ws3; append_layout $layout_dev_base'
# exec --no-startup-id i3-msg 'workspace $ws4; append_layout $layout_dev_base'
# exec --no-startup-id i3-msg 'workspace $ws5; append_layout $layout_dev_base'
# exec --no-startup-id i3-msg 'workspace $ws6; append_layout $layout_dev_base'


# exec --no-startup-id i3-msg workspace 11
# exec --no-startup-id i3-msg workspace $ws0
# exec --no-startup-id i3-msg workspace 11
# exec --no-startup-id i3-msg workspace $ws0
