# vim:syntax=i3config
# Custom Colours
set $c1 		#E62727
set $c2 		#F3F2EC
set $c3 		#DCDCDC
set $c4 		#1E93AB
set $white 		#FFFFFF
set $black		#000000

set $bg-color 	        #1E93AB
set $inactive-bg-color  #222222
set $text-color          #333333
set $inactive-text-color #888888
set $urgent-bg-color     #E62727

# window colors
#                       border              background         text                 indicator
client.focused          $bg-color           $bg-color          $text-color          #00ff00
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color #00ff00
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color #00ff00
client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          #00ff00


font pango:RecMonoCasualNerdFontMono 16

default_border pixel 2
default_floating_border pixel 2
