#!/usr/bin/env bash


export TZ=Europe/Warsaw
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt udpate -y
sudo apt install -y curl git software-properties-common ansible

# sudo ansible-pull -U https://github.com/lppl/ansible.git
