# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# git:
#   paging:
#     paging:
#       colorArg: always
#       pager: "delta"
#       useConfig: false
#       externalDiffCommand: "delta"
# gui:
#   sidePanelWidth: 0.3

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

  commitPrefix:
    - pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] '

    # The final fallthrough regex that copies over the whole branch name
    - pattern: ".*"
      replace : 'Update $0'
gui:
  sidePanelWidth: 0.2
  nerdFontsVersion: 3
  authorColors:
    'Lukasz Pietrek': 'red'
    '*': '#0000ff'
  branchColorPatterns:
    '^docs/': '#11aaff' 
    'ISSUE-\d+': '#ff5733' 

