#!/usr/bin/env bash

sudo apt install -y zip

rm -rf /tmp/awscli
mkdir -p /tmp/awscli

pushd /tmp/awscli

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

popd
