#!/usr/bin/env bash

sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install -y fish

curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
omf install bobthefish

USER=`whoami`
FISH=`which fish`
sudo chsh -s $FISH $USER
