#!/usr/bin/env bash


font_dir="~/.local/share/fonts"
mkdir -p $font_dir

pushd $font_dir
curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
popd
